[project]
site_name = "Wormhole Portal"
site_description = "Unreal Engine용 Wormhole Portal 플러그인 공식 문서입니다."
site_author = "Team Beaver Studio"
site_url = "https://teambeaverstudio.github.io/WormholePortal_Docs/ko/"
docs_dir = "docs-ko"
site_dir = "site-ko"
copyright = """
Copyright &copy; 2026 Team Beaver Studio
"""
nav = [
  { "홈" = "index.md" },
  { "시작하기" = "getting-started/index.md" },
  { "기능" = "features/index.md" },
  { "데모" = "demo/index.md" },
  { "레퍼런스" = "reference.md" },
  { "문제 해결" = "issues/index.md" },
  { "자주 묻는 질문" = "faq/index.md" },
  { "호환성 및 지원" = "support/index.md" },
]
extra_css = [
  "/WormholePortal_Docs/stylesheets/header.css",
  "/WormholePortal_Docs/stylesheets/home.css",
]

[project.extra]
alternate = [
  { name = "English", link = "/WormholePortal_Docs/", lang = "en" },
  { name = "한국어", link = "/WormholePortal_Docs/ko/", lang = "ko" },
]

[project.theme]
custom_dir = "overrides"
language = "ko"
features = [
  "content.code.copy",
  "navigation.footer",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
]

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "라이트 모드로 전환"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "다크 모드로 전환"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "시스템 테마 사용"

[project.markdown_extensions.attr_list]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.toc]
permalink = true
[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.superfences]
